### PR TITLE
Upgrade to ndk-sys 0.5.0 and ndk 0.8.0

### PR DESCRIPTION
**Pull request by rib**

### CODE REVIEW

**Comment by MarijnS95** [comment]
Duplicate of #128?

**Review by MarijnS95 — CHANGES_REQUESTED** [review]
This won't compile due to breaking changes, and #128 is already open to correct that.

**Comment by rib** [comment]
ah yep, np will merge that one thanks

**Comment by rib** [comment]
Closing as dup of #128

**Pull request closed without merging**
